name: Dynamic Workflow for Multi-Stage Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy (e.g., dev, staging, production)"
        required: true
        default: "dev"
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  deploy-development:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' || inputs.branch == 'dev' }}
    steps:
      - name: Deploy to Development
        run: echo "Deploying to Development"

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/staging' || inputs.branch == 'staging' }}
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || inputs.branch == 'production' }}
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"
