name: Conditional Multi-Stage Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy (e.g., dev, staging, production)"
        required: false # Branch input is optional
        default: ""

jobs:
  validate-input:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is provided
        run: |
          if [ "${{ github.event.inputs.branch || github.ref_name }}" == "" ]; then
            echo "No branch provided or detected. Exiting workflow."
            exit 1
          fi

  build:
    needs: validate-input
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  deploy-development:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.branch == 'dev' || github.ref_name == 'dev' }}
    steps:
      - name: Deploy to Development
        run: echo "Deploying to Development"

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.branch == 'staging' || github.ref_name == 'staging' }}
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"

  deploy-master:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.branch == 'master' || github.ref_name == 'master' }}
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"
        
  
