name: Deploy to AWS Lambda

on:
  workflow_dispatch:
    inputs:
      docker_build:
        description: 'Set to true to build Docker image and update Lambda function'
        required: true
        default: 'false'
        type: string
      update_envs:
        description: 'Set to true to update Lambda environment variables'
        required: true
        default: 'false'
        type: string

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: <your-account-id>.dkr.ecr.$AWS_REGION.amazonaws.com
  ECR_REPOSITORY: your-ecr-repo
  LAMBDA_FUNCTION_NAME: your-lambda-function

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      if: ${{ github.event.inputs.docker_build == 'true' }}
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      if: ${{ github.event.inputs.docker_build == 'true' }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build and push Docker image
      if: ${{ github.event.inputs.docker_build == 'true' }}
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Lambda function with the new Docker image
      if: ${{ github.event.inputs.docker_build == 'true' }}
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Lambda environment variables
      if: ${{ github.event.inputs.update_envs == 'true' }}
      run: |
        aws lambda update-function-configuration \
          --function-name $LAMBDA_FUNCTION_NAME \
          --environment "Variables={DB_HOST=localhost,DB_PORT=5432,...}"  # Add your environment variables here
